name: Aws deployment

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.18"

      - name: Build
        run: go build -o bin/application

      - name: Zip it
        run: zip -r go.zip bin go.mod

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ vars.AWS_APPLICATION_NAME }}
          environment_name: ${{ vars.AWS_ENVIRONMENT_NAME }}
          version_label: 1.1.8
          region: eu-central-1
          deployment_package: go.zip
